
const data = [
  {
    "front_field_main": "The Harvard architecture for micro-controllers added which additional bus?",
    "answer_main": "Instruction",
    "count_easy": 0,
    "count_moderate": 0,
    "count_hard": 0,
    "count_again": 0,
    "deck": ["Default", "CS"],
    "score": 10,
    "times_viewed": 0,
    "last_viewed": 0,
    "owner": "Dave",
    "uri": "('../../assets/paper1.jpg')",
    "_id": 0,
  },
  {
    "front_field_main": "Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?",
    "answer_main": "Apple",
    "count_easy": 0,
    "count_moderate": 0,
    "count_hard": 0,
    "count_again": 0,
    "deck": ["Default", "CS"],
    "score": 10,
    "times_viewed": 0,
    "last_viewed": 0,
    "owner": "Dave",
    "uri": "require('../../assets/paper2.jpg')",
    "_id": 1,
  },
  {
    "front_field_main": "An octopus can fit through any hole larger than its beak. True or false?",
    "answer_main": "True",
    "count_easy": 0,
    "count_moderate": 0,
    "count_hard": 0,
    "count_again": 0,
    "deck": ["Default", "Animals"],
    "score": 10,
    "times_viewed": 0,
    "last_viewed": 0,
    "owner": "Dave",
    "uri": "require('../../assets/paper3.jpg')",
    "_id": 2,
  },
  {
    "front_field_main": "Ada Lovelace is often considered the first computer programmer. True or false?",
    "answer_main": "True",
    "count_easy": 0,
    "count_moderate": 0,
    "count_hard": 0,
    "count_again": 0,
    "deck": ["Default", "CS"],
    "score": 10,
    "times_viewed": 0,
    "last_viewed": 0,
    "owner": "Dave",
    "uri": "require('../../assets/4.jpg')",
    "_id": 3,
  },
  {
    "front_field_main": "What is the largest freshwater lake by volume? Lake Superior, Lake Huron, Lake Michigan, Lake Baikal,",
    "answer_main": "Lake Baikal",
    "count_easy": 0,
    "count_moderate": 0,
    "count_hard": 0,
    "count_again": 0,
    "deck": ["Default", "CS"],
    "score": 10,
    "times_viewed": 0,
    "last_viewed": 0,
    "owner": "Dave",
    "uri": "require('../../assets/m.jpg')",
    "_id": 4,
  },
  {
    "front_field_main": "Greenland is a part of which kingdom?",
    "answer_main": "Denmark",
    "count_easy": 0,
    "count_moderate": 0,
    "count_hard": 0,
    "count_again": 0,
    "deck": ["Default", "CS"],
    "score": 10,
    "times_viewed": 0,
    "last_viewed": 0,
    "owner": "Dave",
    "uri": "require('../../assets/e.jpg')",
    "_id": 5,
  },
  {
    "front_field_main": "What was the African nation of Zimbabwe formerly known as?",
    "answer_main": "Rhodesia",
    "count_easy": 0,
    "count_moderate": 0,
    "count_hard": 0,
    "count_again": 0,
    "deck": ["Default", "CS"],
    "score": 10,
    "times_viewed": 0,
    "last_viewed": 0,
    "owner": "Dave",
    "uri": "require('../../assets/c.jpg')",
    "_id": 6,
  },
  {
    "front_field_main": "Which of these Japanese islands is the largest by area? Shikoku, Iki, Odaiba, Okinawa",
    "answer_main": "Shikoku",
    "count_easy": 0,
    "count_moderate": 0,
    "count_hard": 0,
    "count_again": 0,
    "deck": ["Default"],
    "score": 10,
    "times_viewed": 0,
    "last_viewed": 0,
    "owner": "Dave",
    "uri": "require('../../assets/e.jpg')",
    "_id": 7,
  },
]

export default data;
